/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugIndexRouteImport } from './routes/$slug/index'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedLandingPageRouteImport } from './routes/_authenticated/landing-page'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as SlugLinktreeRouteImport } from './routes/$slug/linktree'
import { Route as AuthenticatedKontenIndexRouteImport } from './routes/_authenticated/konten/index'
import { Route as AuthenticatedKontenBaruRouteImport } from './routes/_authenticated/konten/baru'
import { Route as AuthenticatedKontenIdRouteImport } from './routes/_authenticated/konten/$id'
import { Route as SlugProdukProductIdRouteImport } from './routes/$slug/produk/$productId'
import { Route as AuthenticatedConnectMetaCallbackRouteImport } from './routes/_authenticated/connect/meta/callback'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLandingPageRoute =
  AuthenticatedLandingPageRouteImport.update({
    id: '/landing-page',
    path: '/landing-page',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SlugLinktreeRoute = SlugLinktreeRouteImport.update({
  id: '/$slug/linktree',
  path: '/$slug/linktree',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKontenIndexRoute =
  AuthenticatedKontenIndexRouteImport.update({
    id: '/konten/',
    path: '/konten/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKontenBaruRoute = AuthenticatedKontenBaruRouteImport.update({
  id: '/konten/baru',
  path: '/konten/baru',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKontenIdRoute = AuthenticatedKontenIdRouteImport.update({
  id: '/konten/$id',
  path: '/konten/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SlugProdukProductIdRoute = SlugProdukProductIdRouteImport.update({
  id: '/$slug/produk/$productId',
  path: '/$slug/produk/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConnectMetaCallbackRoute =
  AuthenticatedConnectMetaCallbackRouteImport.update({
    id: '/connect/meta/callback',
    path: '/connect/meta/callback',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/$slug/linktree': typeof SlugLinktreeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/landing-page': typeof AuthenticatedLandingPageRoute
  '/products': typeof AuthenticatedProductsRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/produk/$productId': typeof SlugProdukProductIdRoute
  '/konten/$id': typeof AuthenticatedKontenIdRoute
  '/konten/baru': typeof AuthenticatedKontenBaruRoute
  '/konten/': typeof AuthenticatedKontenIndexRoute
  '/connect/meta/callback': typeof AuthenticatedConnectMetaCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/$slug/linktree': typeof SlugLinktreeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/landing-page': typeof AuthenticatedLandingPageRoute
  '/products': typeof AuthenticatedProductsRoute
  '/$slug': typeof SlugIndexRoute
  '/$slug/produk/$productId': typeof SlugProdukProductIdRoute
  '/konten/$id': typeof AuthenticatedKontenIdRoute
  '/konten/baru': typeof AuthenticatedKontenBaruRoute
  '/konten': typeof AuthenticatedKontenIndexRoute
  '/connect/meta/callback': typeof AuthenticatedConnectMetaCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/$slug/linktree': typeof SlugLinktreeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/landing-page': typeof AuthenticatedLandingPageRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/produk/$productId': typeof SlugProdukProductIdRoute
  '/_authenticated/konten/$id': typeof AuthenticatedKontenIdRoute
  '/_authenticated/konten/baru': typeof AuthenticatedKontenBaruRoute
  '/_authenticated/konten/': typeof AuthenticatedKontenIndexRoute
  '/_authenticated/connect/meta/callback': typeof AuthenticatedConnectMetaCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/$slug/linktree'
    | '/dashboard'
    | '/integrations'
    | '/landing-page'
    | '/products'
    | '/$slug/'
    | '/$slug/produk/$productId'
    | '/konten/$id'
    | '/konten/baru'
    | '/konten/'
    | '/connect/meta/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/$slug/linktree'
    | '/dashboard'
    | '/integrations'
    | '/landing-page'
    | '/products'
    | '/$slug'
    | '/$slug/produk/$productId'
    | '/konten/$id'
    | '/konten/baru'
    | '/konten'
    | '/connect/meta/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/login'
    | '/$slug/linktree'
    | '/_authenticated/dashboard'
    | '/_authenticated/integrations'
    | '/_authenticated/landing-page'
    | '/_authenticated/products'
    | '/$slug/'
    | '/$slug/produk/$productId'
    | '/_authenticated/konten/$id'
    | '/_authenticated/konten/baru'
    | '/_authenticated/konten/'
    | '/_authenticated/connect/meta/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  SlugLinktreeRoute: typeof SlugLinktreeRoute
  SlugIndexRoute: typeof SlugIndexRoute
  SlugProdukProductIdRoute: typeof SlugProdukProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/$slug'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/landing-page': {
      id: '/_authenticated/landing-page'
      path: '/landing-page'
      fullPath: '/landing-page'
      preLoaderRoute: typeof AuthenticatedLandingPageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/$slug/linktree': {
      id: '/$slug/linktree'
      path: '/$slug/linktree'
      fullPath: '/$slug/linktree'
      preLoaderRoute: typeof SlugLinktreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/konten/': {
      id: '/_authenticated/konten/'
      path: '/konten'
      fullPath: '/konten/'
      preLoaderRoute: typeof AuthenticatedKontenIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/konten/baru': {
      id: '/_authenticated/konten/baru'
      path: '/konten/baru'
      fullPath: '/konten/baru'
      preLoaderRoute: typeof AuthenticatedKontenBaruRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/konten/$id': {
      id: '/_authenticated/konten/$id'
      path: '/konten/$id'
      fullPath: '/konten/$id'
      preLoaderRoute: typeof AuthenticatedKontenIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/$slug/produk/$productId': {
      id: '/$slug/produk/$productId'
      path: '/$slug/produk/$productId'
      fullPath: '/$slug/produk/$productId'
      preLoaderRoute: typeof SlugProdukProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/connect/meta/callback': {
      id: '/_authenticated/connect/meta/callback'
      path: '/connect/meta/callback'
      fullPath: '/connect/meta/callback'
      preLoaderRoute: typeof AuthenticatedConnectMetaCallbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedLandingPageRoute: typeof AuthenticatedLandingPageRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedKontenIdRoute: typeof AuthenticatedKontenIdRoute
  AuthenticatedKontenBaruRoute: typeof AuthenticatedKontenBaruRoute
  AuthenticatedKontenIndexRoute: typeof AuthenticatedKontenIndexRoute
  AuthenticatedConnectMetaCallbackRoute: typeof AuthenticatedConnectMetaCallbackRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedLandingPageRoute: AuthenticatedLandingPageRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedKontenIdRoute: AuthenticatedKontenIdRoute,
  AuthenticatedKontenBaruRoute: AuthenticatedKontenBaruRoute,
  AuthenticatedKontenIndexRoute: AuthenticatedKontenIndexRoute,
  AuthenticatedConnectMetaCallbackRoute: AuthenticatedConnectMetaCallbackRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  SlugLinktreeRoute: SlugLinktreeRoute,
  SlugIndexRoute: SlugIndexRoute,
  SlugProdukProductIdRoute: SlugProdukProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
